/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_jpeg_turbo_demo_Util */

#ifndef _Included_com_sun_jpeg_turbo_demo_Util
#define _Included_com_sun_jpeg_turbo_demo_Util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_jpeg_turbo_demo_Util
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_jpeg_turbo_demo_Util_read
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
